// Generated by Haxe 4.3.6

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hxDaedalus.data.math {
	public class Point2D : global::haxe.lang.HxObject {
		
		public Point2D(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public Point2D(global::haxe.lang.Null<double> x_, global::haxe.lang.Null<double> y_) {
			global::hxDaedalus.data.math.Point2D.__hx_ctor_hxDaedalus_data_math_Point2D(this, x_, y_);
		}
		
		
		protected static void __hx_ctor_hxDaedalus_data_math_Point2D(global::hxDaedalus.data.math.Point2D __hx_this, global::haxe.lang.Null<double> x_, global::haxe.lang.Null<double> y_) {
			double y_1 = ( ( ! (y_.hasValue) ) ? (((double) (0) )) : ((y_).@value) );
			double x_1 = ( ( ! (x_.hasValue) ) ? (((double) (0) )) : ((x_).@value) );
			__hx_this.x = x_1;
			__hx_this.y = y_1;
		}
		
		
		
		
		public double x;
		
		public double y;
		
		public virtual void transform(global::hxDaedalus.data.math.Matrix2D matrix) {
			matrix.tranform(this);
		}
		
		
		public virtual void setXY(double x_, double y_) {
			this.x = x_;
			this.y = y_;
		}
		
		
		public virtual global::hxDaedalus.data.math.Point2D clone() {
			return new global::hxDaedalus.data.math.Point2D(new global::haxe.lang.Null<double>(this.x, true), new global::haxe.lang.Null<double>(this.y, true));
		}
		
		
		public virtual void substract(global::hxDaedalus.data.math.Point2D p) {
			this.x -= p.x;
			this.y -= p.y;
		}
		
		
		public virtual double get_length() {
			return global::System.Math.Sqrt(((double) (( ( this.x * this.x ) + ( this.y * this.y ) )) ));
		}
		
		
		public virtual void normalize() {
			double norm = this.get_length();
			this.x /= norm;
			this.y /= norm;
		}
		
		
		public virtual void scale(double s) {
			this.x *= s;
			this.y *= s;
		}
		
		
		public virtual double distanceTo(global::hxDaedalus.data.math.Point2D p) {
			double diffX = ( this.x - p.x );
			double diffY = ( this.y - p.y );
			return global::System.Math.Sqrt(((double) (( ( diffX * diffX ) + ( diffY * diffY ) )) ));
		}
		
		
		public override double __hx_setField_f(string field, int hash, double @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 121:
					{
						this.y = ((double) (@value) );
						return @value;
					}
					
					
					case 120:
					{
						this.x = ((double) (@value) );
						return @value;
					}
					
					
					default:
					{
						return base.__hx_setField_f(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 121:
					{
						this.y = ((double) (global::haxe.lang.Runtime.toDouble(@value)) );
						return @value;
					}
					
					
					case 120:
					{
						this.x = ((double) (global::haxe.lang.Runtime.toDouble(@value)) );
						return @value;
					}
					
					
					default:
					{
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 200070160:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "distanceTo", 200070160)) );
					}
					
					
					case 2026819210:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "scale", 2026819210)) );
					}
					
					
					case 731985805:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "normalize", 731985805)) );
					}
					
					
					case 261031087:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "get_length", 261031087)) );
					}
					
					
					case 1658967745:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "substract", 1658967745)) );
					}
					
					
					case 1214452573:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "clone", 1214452573)) );
					}
					
					
					case 2049938723:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "setXY", 2049938723)) );
					}
					
					
					case 1167273324:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "transform", 1167273324)) );
					}
					
					
					case 121:
					{
						return this.y;
					}
					
					
					case 120:
					{
						return this.x;
					}
					
					
					case 520590566:
					{
						return this.get_length();
					}
					
					
					default:
					{
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override double __hx_getField_f(string field, int hash, bool throwErrors, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 121:
					{
						return this.y;
					}
					
					
					case 120:
					{
						return this.x;
					}
					
					
					case 520590566:
					{
						return this.get_length();
					}
					
					
					default:
					{
						return base.__hx_getField_f(field, hash, throwErrors, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_invokeField(string field, int hash, object[] dynargs) {
			unchecked {
				switch (hash) {
					case 200070160:
					{
						return this.distanceTo(((global::hxDaedalus.data.math.Point2D) (dynargs[0]) ));
					}
					
					
					case 2026819210:
					{
						this.scale(((double) (global::haxe.lang.Runtime.toDouble(dynargs[0])) ));
						break;
					}
					
					
					case 731985805:
					{
						this.normalize();
						break;
					}
					
					
					case 261031087:
					{
						return this.get_length();
					}
					
					
					case 1658967745:
					{
						this.substract(((global::hxDaedalus.data.math.Point2D) (dynargs[0]) ));
						break;
					}
					
					
					case 1214452573:
					{
						return this.clone();
					}
					
					
					case 2049938723:
					{
						this.setXY(((double) (global::haxe.lang.Runtime.toDouble(dynargs[0])) ), ((double) (global::haxe.lang.Runtime.toDouble(dynargs[1])) ));
						break;
					}
					
					
					case 1167273324:
					{
						this.transform(((global::hxDaedalus.data.math.Matrix2D) (dynargs[0]) ));
						break;
					}
					
					
					default:
					{
						return base.__hx_invokeField(field, hash, dynargs);
					}
					
				}
				
				return null;
			}
		}
		
		
		public override void __hx_getFields(global::HxArray<string> baseArr) {
			baseArr.push("y");
			baseArr.push("x");
			baseArr.push("length");
			base.__hx_getFields(baseArr);
		}
		
		
	}
}


