// Generated by Haxe 4.3.6

#pragma warning disable 109, 114, 219, 429, 168, 162
using Pathfinding.Util;

namespace hxDaedalus.data {
	public class ConstraintSegment : global::haxe.lang.HxObject {
		
		static ConstraintSegment() {
			global::hxDaedalus.data.ConstraintSegment.INC = 0;
		}
		
		
		public ConstraintSegment(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public ConstraintSegment() {
			global::hxDaedalus.data.ConstraintSegment.__hx_ctor_hxDaedalus_data_ConstraintSegment(this);
		}
		
		
		protected static void __hx_ctor_hxDaedalus_data_ConstraintSegment(global::hxDaedalus.data.ConstraintSegment __hx_this) {
			__hx_this._id = global::hxDaedalus.data.ConstraintSegment.INC;
			global::hxDaedalus.data.ConstraintSegment.INC++;
			__hx_this._edges = new global::HxArray<object>();
		}
		
		
		public static int INC;
		
		
		
		public global::hxDaedalus.data.ConstraintShape fromShape;
		
		
		
		public int _id;
		
		public global::HxArray<object> _edges;
		
		public virtual int get_id() {
			return this._id;
		}
		
		
		public virtual void addEdge(global::hxDaedalus.data.Edge edge) {
			unchecked {
				if (( ( this._edges.indexOf(edge, default(global::haxe.lang.Null<int>)) == -1 ) && ( this._edges.indexOf(edge.get_oppositeEdge(), default(global::haxe.lang.Null<int>)) == -1 ) )) {
                    Debug.LogToFile($"ConstraintSegment addEdge id:{_id}, edge_id:{edge._id}");
                    this._edges.push(edge);
				}
				
			}
		}
		
		
		public virtual void removeEdge(global::hxDaedalus.data.Edge edge) {
			unchecked {
				int index = this._edges.indexOf(edge, default(global::haxe.lang.Null<int>));
				if (( index == -1 )) {
					index = this._edges.indexOf(edge.get_oppositeEdge(), default(global::haxe.lang.Null<int>));
				}
				
				if (( index != -1 )) {
                    Debug.LogToFile($"ConstraintSegment removeEdge id:{_id}, edge_id:{edge._id}, index:{index}");
                    this._edges.spliceVoid(index, 1);
				}
				
			}
		}
		
		
		public virtual global::HxArray<object> get_edges() {
			return this._edges;
		}
		
		
		public virtual void dispose() {
			this._edges = null;
			this.fromShape = null;
		}
		
		
		public virtual string toString() {
			return global::haxe.lang.Runtime.concat("seg_id ", global::haxe.lang.Runtime.toString(this._id));
		}
		
		
		public override double __hx_setField_f(string field, int hash, double @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 4747770:
					{
						this._id = ((int) (@value) );
						return @value;
					}
					
					
					default:
					{
						return base.__hx_setField_f(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1707586775:
					{
						this._edges = ((global::HxArray<object>) (global::HxArray<object>.__hx_cast<object>(((global::HxArray) (@value) ))) );
						return @value;
					}
					
					
					case 4747770:
					{
						this._id = ((int) (global::haxe.lang.Runtime.toInt(@value)) );
						return @value;
					}
					
					
					case 816172375:
					{
						this.fromShape = ((global::hxDaedalus.data.ConstraintShape) (@value) );
						return @value;
					}
					
					
					default:
					{
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 946786476:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "toString", 946786476)) );
					}
					
					
					case 994869407:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "dispose", 994869407)) );
					}
					
					
					case 764004845:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "get_edges", 764004845)) );
					}
					
					
					case 1076757153:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "removeEdge", 1076757153)) );
					}
					
					
					case 2135689982:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "addEdge", 2135689982)) );
					}
					
					
					case 590344996:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "get_id", 590344996)) );
					}
					
					
					case 1707586775:
					{
						return this._edges;
					}
					
					
					case 4747770:
					{
						return this._id;
					}
					
					
					case 1776315798:
					{
						return this.get_edges();
					}
					
					
					case 816172375:
					{
						return this.fromShape;
					}
					
					
					case 23515:
					{
						return this.get_id();
					}
					
					
					default:
					{
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override double __hx_getField_f(string field, int hash, bool throwErrors, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 4747770:
					{
						return ((double) (this._id) );
					}
					
					
					case 23515:
					{
						return ((double) (this.get_id()) );
					}
					
					
					default:
					{
						return base.__hx_getField_f(field, hash, throwErrors, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_invokeField(string field, int hash, object[] dynargs) {
			unchecked {
				switch (hash) {
					case 946786476:
					{
						return this.toString();
					}
					
					
					case 994869407:
					{
						this.dispose();
						break;
					}
					
					
					case 764004845:
					{
						return this.get_edges();
					}
					
					
					case 1076757153:
					{
						this.removeEdge(((global::hxDaedalus.data.Edge) (dynargs[0]) ));
						break;
					}
					
					
					case 2135689982:
					{
						this.addEdge(((global::hxDaedalus.data.Edge) (dynargs[0]) ));
						break;
					}
					
					
					case 590344996:
					{
						return this.get_id();
					}
					
					
					default:
					{
						return base.__hx_invokeField(field, hash, dynargs);
					}
					
				}
				
				return null;
			}
		}
		
		
		public override void __hx_getFields(global::HxArray<string> baseArr) {
			baseArr.push("_edges");
			baseArr.push("_id");
			baseArr.push("edges");
			baseArr.push("fromShape");
			baseArr.push("id");
			base.__hx_getFields(baseArr);
		}
		
		
		public override string ToString(){
			return this.toString();
		}
		
		
	}
}


