// Generated by Haxe 4.3.6

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hxDaedalus.data {
	public class Constants : global::haxe.lang.HxObject {
		
		static Constants() {
			global::hxDaedalus.data.Constants.EPSILON = 0.01;
			global::hxDaedalus.data.Constants.EPSILON_SQUARED = 0.0001;
		}
		
		
		public Constants(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public Constants() {
			global::hxDaedalus.data.Constants.__hx_ctor_hxDaedalus_data_Constants(this);
		}
		
		
		protected static void __hx_ctor_hxDaedalus_data_Constants(global::hxDaedalus.data.Constants __hx_this) {
		}
		
		
		public static double EPSILON;
		
		public static double EPSILON_SQUARED;
		
	}
}


