// Generated by Haxe 4.3.6

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hxDaedalus.data {
	public class Face : global::haxe.lang.HxObject {
		
		static Face() {
			global::hxDaedalus.data.Face.INC = 0;
		}
		
		
		public Face(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public Face() {
			global::hxDaedalus.data.Face.__hx_ctor_hxDaedalus_data_Face(this);
		}
		
		
		protected static void __hx_ctor_hxDaedalus_data_Face(global::hxDaedalus.data.Face __hx_this) {
			unchecked {
				__hx_this.colorDebug = -1;
				{
					__hx_this._id = global::hxDaedalus.data.Face.INC;
					global::hxDaedalus.data.Face.INC++;
				}
				
			}
		}
		
		
		public static int INC;
		
		
		
		
		
		
		
		public int _id;
		
		public bool _isReal;
		
		public global::hxDaedalus.data.Edge _edge;
		
		public int colorDebug;
		
		public virtual int get_id() {
			return this._id;
		}
		
		
		public virtual bool get_isReal() {
			return this._isReal;
		}
		
		
		public virtual void set_datas(global::hxDaedalus.data.Edge edge) {
			this._isReal = true;
			this._edge = edge;
		}
		
		
		public virtual void setDatas(global::hxDaedalus.data.Edge edge, global::haxe.lang.Null<bool> isReal) {
			bool isReal1 = ( ( ! (isReal.hasValue) ) ? (true) : ((isReal).@value) );
			this._isReal = isReal1;
			this._edge = edge;
		}
		
		
		public virtual void dispose() {
			this._edge = null;
		}
		
		
		public virtual global::hxDaedalus.data.Edge get_edge() {
			return this._edge;
		}
		
		
		public override double __hx_setField_f(string field, int hash, double @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 2072734192:
					{
						this.colorDebug = ((int) (@value) );
						return @value;
					}
					
					
					case 4747770:
					{
						this._id = ((int) (@value) );
						return @value;
					}
					
					
					default:
					{
						return base.__hx_setField_f(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 2072734192:
					{
						this.colorDebug = ((int) (global::haxe.lang.Runtime.toInt(@value)) );
						return @value;
					}
					
					
					case 1981801500:
					{
						this._edge = ((global::hxDaedalus.data.Edge) (@value) );
						return @value;
					}
					
					
					case 1468342791:
					{
						this._isReal = global::haxe.lang.Runtime.toBool(@value);
						return @value;
					}
					
					
					case 4747770:
					{
						this._id = ((int) (global::haxe.lang.Runtime.toInt(@value)) );
						return @value;
					}
					
					
					default:
					{
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1120502726:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "get_edge", 1120502726)) );
					}
					
					
					case 994869407:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "dispose", 994869407)) );
					}
					
					
					case 1656518663:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "setDatas", 1656518663)) );
					}
					
					
					case 2072139628:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "set_datas", 2072139628)) );
					}
					
					
					case 1502969905:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "get_isReal", 1502969905)) );
					}
					
					
					case 590344996:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "get_id", 590344996)) );
					}
					
					
					case 2072734192:
					{
						return this.colorDebug;
					}
					
					
					case 1981801500:
					{
						return this._edge;
					}
					
					
					case 1468342791:
					{
						return this._isReal;
					}
					
					
					case 4747770:
					{
						return this._id;
					}
					
					
					case 1125042237:
					{
						return this.get_edge();
					}
					
					
					case 1762529384:
					{
						return this.get_isReal();
					}
					
					
					case 23515:
					{
						return this.get_id();
					}
					
					
					default:
					{
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override double __hx_getField_f(string field, int hash, bool throwErrors, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 2072734192:
					{
						return ((double) (this.colorDebug) );
					}
					
					
					case 4747770:
					{
						return ((double) (this._id) );
					}
					
					
					case 23515:
					{
						return ((double) (this.get_id()) );
					}
					
					
					default:
					{
						return base.__hx_getField_f(field, hash, throwErrors, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_invokeField(string field, int hash, object[] dynargs) {
			unchecked {
				switch (hash) {
					case 1120502726:
					{
						return this.get_edge();
					}
					
					
					case 994869407:
					{
						this.dispose();
						break;
					}
					
					
					case 1656518663:
					{
						this.setDatas(((global::hxDaedalus.data.Edge) (dynargs[0]) ), global::haxe.lang.Null<object>.ofDynamic<bool>(( (( dynargs.Length > 1 )) ? (dynargs[1]) : (null) )));
						break;
					}
					
					
					case 2072139628:
					{
						this.set_datas(((global::hxDaedalus.data.Edge) (dynargs[0]) ));
						break;
					}
					
					
					case 1502969905:
					{
						return this.get_isReal();
					}
					
					
					case 590344996:
					{
						return this.get_id();
					}
					
					
					default:
					{
						return base.__hx_invokeField(field, hash, dynargs);
					}
					
				}
				
				return null;
			}
		}
		
		
		public override void __hx_getFields(global::HxArray<string> baseArr) {
			baseArr.push("colorDebug");
			baseArr.push("_edge");
			baseArr.push("_isReal");
			baseArr.push("_id");
			baseArr.push("edge");
			baseArr.push("isReal");
			baseArr.push("id");
			base.__hx_getFields(baseArr);
		}
		
		
	}
}


