// Generated by Haxe 4.3.6

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hxDaedalus.data {
	public class Vertex : global::haxe.lang.HxObject {
		
		static Vertex() {
			global::hxDaedalus.data.Vertex.INC = 0;
		}
		
		
		public Vertex(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public Vertex() {
			global::hxDaedalus.data.Vertex.__hx_ctor_hxDaedalus_data_Vertex(this);
		}
		
		
		protected static void __hx_ctor_hxDaedalus_data_Vertex(global::hxDaedalus.data.Vertex __hx_this) {
			unchecked {
				__hx_this.colorDebug = -1;
				{
					__hx_this._id = global::hxDaedalus.data.Vertex.INC;
					global::hxDaedalus.data.Vertex.INC++;
					__hx_this._pos = new global::hxDaedalus.data.math.Point2D(default(global::haxe.lang.Null<double>), default(global::haxe.lang.Null<double>));
					__hx_this._fromConstraintSegments = new global::HxArray<object>();
				}
				
			}
		}
		
		
		public static int INC;
		
		
		
		
		
		
		
		
		
		
		
		public int _id;
		
		public global::hxDaedalus.data.math.Point2D _pos;
		
		public bool _isReal;
		
		public global::hxDaedalus.data.Edge _edge;
		
		public global::HxArray<object> _fromConstraintSegments;
		
		public int colorDebug;
		
		public virtual int get_id() {
			return this._id;
		}
		
		
		public virtual bool get_isReal() {
			return this._isReal;
		}
		
		
		public virtual global::hxDaedalus.data.math.Point2D get_pos() {
			return this._pos;
		}
		
		
		public virtual global::HxArray<object> get_fromConstraintSegments() {
			return this._fromConstraintSegments;
		}
		
		
		public virtual global::HxArray<object> set_fromConstraintSegments(global::HxArray<object> @value) {
			return this._fromConstraintSegments = @value;
		}
		
		
		public virtual void setDatas(global::hxDaedalus.data.Edge edge, global::haxe.lang.Null<bool> isReal) {
			bool isReal1 = ( ( ! (isReal.hasValue) ) ? (true) : ((isReal).@value) );
			this._isReal = isReal1;
			this._edge = edge;
		}
		
		
		public virtual void addFromConstraintSegment(global::hxDaedalus.data.ConstraintSegment segment) {
			unchecked {
				if (( this._fromConstraintSegments.indexOf(segment, default(global::haxe.lang.Null<int>)) == -1 )) {
					this._fromConstraintSegments.push(segment);
				}
				
			}
		}
		
		
		public virtual void removeFromConstraintSegment(global::hxDaedalus.data.ConstraintSegment segment) {
			unchecked {
				int index = this._fromConstraintSegments.indexOf(segment, default(global::haxe.lang.Null<int>));
				if (( index != -1 )) {
					this._fromConstraintSegments.spliceVoid(index, 1);
				}
				
			}
		}
		
		
		public virtual void dispose() {
			this._pos = null;
			this._edge = null;
			this._fromConstraintSegments = null;
		}
		
		
		public virtual global::hxDaedalus.data.Edge get_edge() {
			return this._edge;
		}
		
		
		public virtual global::hxDaedalus.data.Edge set_edge(global::hxDaedalus.data.Edge @value) {
			return this._edge = @value;
		}
		
		
		public virtual string toString() {
			return global::haxe.lang.Runtime.concat("ver_id ", global::haxe.lang.Runtime.toString(this._id));
		}
		
		
		public override double __hx_setField_f(string field, int hash, double @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 2072734192:
					{
						this.colorDebug = ((int) (@value) );
						return @value;
					}
					
					
					case 4747770:
					{
						this._id = ((int) (@value) );
						return @value;
					}
					
					
					default:
					{
						return base.__hx_setField_f(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 2072734192:
					{
						this.colorDebug = ((int) (global::haxe.lang.Runtime.toInt(@value)) );
						return @value;
					}
					
					
					case 2020391558:
					{
						this._fromConstraintSegments = ((global::HxArray<object>) (global::HxArray<object>.__hx_cast<object>(((global::HxArray) (@value) ))) );
						return @value;
					}
					
					
					case 1981801500:
					{
						this._edge = ((global::hxDaedalus.data.Edge) (@value) );
						return @value;
					}
					
					
					case 1468342791:
					{
						this._isReal = global::haxe.lang.Runtime.toBool(@value);
						return @value;
					}
					
					
					case 1059103381:
					{
						this._pos = ((global::hxDaedalus.data.math.Point2D) (@value) );
						return @value;
					}
					
					
					case 4747770:
					{
						this._id = ((int) (global::haxe.lang.Runtime.toInt(@value)) );
						return @value;
					}
					
					
					case 1125042237:
					{
						this.set_edge(((global::hxDaedalus.data.Edge) (@value) ));
						return @value;
					}
					
					
					case 1704213223:
					{
						this.set_fromConstraintSegments(((global::HxArray<object>) (global::HxArray<object>.__hx_cast<object>(((global::HxArray) (@value) ))) ));
						return @value;
					}
					
					
					default:
					{
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 946786476:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "toString", 946786476)) );
					}
					
					
					case 1898372410:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "set_edge", 1898372410)) );
					}
					
					
					case 1120502726:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "get_edge", 1120502726)) );
					}
					
					
					case 994869407:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "dispose", 994869407)) );
					}
					
					
					case 1059759400:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "removeFromConstraintSegment", 1059759400)) );
					}
					
					
					case 1813079083:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "addFromConstraintSegment", 1813079083)) );
					}
					
					
					case 1656518663:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "setDatas", 1656518663)) );
					}
					
					
					case 2100187940:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "set_fromConstraintSegments", 2100187940)) );
					}
					
					
					case 496602288:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "get_fromConstraintSegments", 496602288)) );
					}
					
					
					case 650782251:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "get_pos", 650782251)) );
					}
					
					
					case 1502969905:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "get_isReal", 1502969905)) );
					}
					
					
					case 590344996:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "get_id", 590344996)) );
					}
					
					
					case 2072734192:
					{
						return this.colorDebug;
					}
					
					
					case 2020391558:
					{
						return this._fromConstraintSegments;
					}
					
					
					case 1981801500:
					{
						return this._edge;
					}
					
					
					case 1468342791:
					{
						return this._isReal;
					}
					
					
					case 1059103381:
					{
						return this._pos;
					}
					
					
					case 4747770:
					{
						return this._id;
					}
					
					
					case 1125042237:
					{
						return this.get_edge();
					}
					
					
					case 1704213223:
					{
						return this.get_fromConstraintSegments();
					}
					
					
					case 5594516:
					{
						return this.get_pos();
					}
					
					
					case 1762529384:
					{
						return this.get_isReal();
					}
					
					
					case 23515:
					{
						return this.get_id();
					}
					
					
					default:
					{
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override double __hx_getField_f(string field, int hash, bool throwErrors, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 2072734192:
					{
						return ((double) (this.colorDebug) );
					}
					
					
					case 4747770:
					{
						return ((double) (this._id) );
					}
					
					
					case 23515:
					{
						return ((double) (this.get_id()) );
					}
					
					
					default:
					{
						return base.__hx_getField_f(field, hash, throwErrors, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_invokeField(string field, int hash, object[] dynargs) {
			unchecked {
				switch (hash) {
					case 946786476:
					{
						return this.toString();
					}
					
					
					case 1898372410:
					{
						return this.set_edge(((global::hxDaedalus.data.Edge) (dynargs[0]) ));
					}
					
					
					case 1120502726:
					{
						return this.get_edge();
					}
					
					
					case 994869407:
					{
						this.dispose();
						break;
					}
					
					
					case 1059759400:
					{
						this.removeFromConstraintSegment(((global::hxDaedalus.data.ConstraintSegment) (dynargs[0]) ));
						break;
					}
					
					
					case 1813079083:
					{
						this.addFromConstraintSegment(((global::hxDaedalus.data.ConstraintSegment) (dynargs[0]) ));
						break;
					}
					
					
					case 1656518663:
					{
						this.setDatas(((global::hxDaedalus.data.Edge) (dynargs[0]) ), global::haxe.lang.Null<object>.ofDynamic<bool>(( (( dynargs.Length > 1 )) ? (dynargs[1]) : (null) )));
						break;
					}
					
					
					case 2100187940:
					{
						return this.set_fromConstraintSegments(((global::HxArray<object>) (global::HxArray<object>.__hx_cast<object>(((global::HxArray) (dynargs[0]) ))) ));
					}
					
					
					case 496602288:
					{
						return this.get_fromConstraintSegments();
					}
					
					
					case 650782251:
					{
						return this.get_pos();
					}
					
					
					case 1502969905:
					{
						return this.get_isReal();
					}
					
					
					case 590344996:
					{
						return this.get_id();
					}
					
					
					default:
					{
						return base.__hx_invokeField(field, hash, dynargs);
					}
					
				}
				
				return null;
			}
		}
		
		
		public override void __hx_getFields(global::HxArray<string> baseArr) {
			baseArr.push("colorDebug");
			baseArr.push("_fromConstraintSegments");
			baseArr.push("_edge");
			baseArr.push("_isReal");
			baseArr.push("_pos");
			baseArr.push("_id");
			baseArr.push("edge");
			baseArr.push("fromConstraintSegments");
			baseArr.push("pos");
			baseArr.push("isReal");
			baseArr.push("id");
			base.__hx_getFields(baseArr);
		}
		
		
		public override string ToString(){
			return this.toString();
		}
		
		
	}
}


