// Generated by Haxe 4.3.6

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hxDaedalus.iterators {
	public class FromMeshToVertices : global::haxe.lang.HxObject {
		
		public FromMeshToVertices(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public FromMeshToVertices() {
			global::hxDaedalus.iterators.FromMeshToVertices.__hx_ctor_hxDaedalus_iterators_FromMeshToVertices(this);
		}
		
		
		protected static void __hx_ctor_hxDaedalus_iterators_FromMeshToVertices(global::hxDaedalus.iterators.FromMeshToVertices __hx_this) {
		}
		
		
		
		
		public global::hxDaedalus.data.Mesh _fromMesh;
		
		public int _currIndex;
		
		public global::hxDaedalus.data.Vertex _resultVertex;
		
		public virtual global::hxDaedalus.data.Mesh set_fromMesh(global::hxDaedalus.data.Mesh @value) {
			this._fromMesh = @value;
			this._currIndex = 0;
			return @value;
		}
		
		
		public virtual global::hxDaedalus.data.Vertex next() {
			do {
				if (( this._currIndex < this._fromMesh._vertices.length )) {
					this._resultVertex = ((global::hxDaedalus.data.Vertex) (this._fromMesh._vertices[this._currIndex]) );
					this._currIndex++;
				}
				else {
					this._resultVertex = null;
					break;
				}
				
			}
			while ( ! (this._resultVertex.get_isReal()) );
			return this._resultVertex;
		}
		
		
		public override double __hx_setField_f(string field, int hash, double @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 2106347137:
					{
						this._currIndex = ((int) (@value) );
						return @value;
					}
					
					
					default:
					{
						return base.__hx_setField_f(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 437571328:
					{
						this._resultVertex = ((global::hxDaedalus.data.Vertex) (@value) );
						return @value;
					}
					
					
					case 2106347137:
					{
						this._currIndex = ((int) (global::haxe.lang.Runtime.toInt(@value)) );
						return @value;
					}
					
					
					case 1840975830:
					{
						this._fromMesh = ((global::hxDaedalus.data.Mesh) (@value) );
						return @value;
					}
					
					
					case 639965303:
					{
						this.set_fromMesh(((global::hxDaedalus.data.Mesh) (@value) ));
						return @value;
					}
					
					
					default:
					{
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1224901875:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "next", 1224901875)) );
					}
					
					
					case 1882714100:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "set_fromMesh", 1882714100)) );
					}
					
					
					case 437571328:
					{
						return this._resultVertex;
					}
					
					
					case 2106347137:
					{
						return this._currIndex;
					}
					
					
					case 1840975830:
					{
						return this._fromMesh;
					}
					
					
					default:
					{
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override double __hx_getField_f(string field, int hash, bool throwErrors, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 2106347137:
					{
						return ((double) (this._currIndex) );
					}
					
					
					default:
					{
						return base.__hx_getField_f(field, hash, throwErrors, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_invokeField(string field, int hash, object[] dynargs) {
			unchecked {
				switch (hash) {
					case 1224901875:
					{
						return this.next();
					}
					
					
					case 1882714100:
					{
						return this.set_fromMesh(((global::hxDaedalus.data.Mesh) (dynargs[0]) ));
					}
					
					
					default:
					{
						return base.__hx_invokeField(field, hash, dynargs);
					}
					
				}
				
			}
		}
		
		
		public override void __hx_getFields(global::HxArray<string> baseArr) {
			baseArr.push("_resultVertex");
			baseArr.push("_currIndex");
			baseArr.push("_fromMesh");
			baseArr.push("fromMesh");
			base.__hx_getFields(baseArr);
		}
		
		
	}
}


