// Generated by Haxe 4.3.6

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hxDaedalus.iterators {
	public class FromFaceToInnerEdges : global::haxe.lang.HxObject {
		
		public FromFaceToInnerEdges(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public FromFaceToInnerEdges() {
			global::hxDaedalus.iterators.FromFaceToInnerEdges.__hx_ctor_hxDaedalus_iterators_FromFaceToInnerEdges(this);
		}
		
		
		protected static void __hx_ctor_hxDaedalus_iterators_FromFaceToInnerEdges(global::hxDaedalus.iterators.FromFaceToInnerEdges __hx_this) {
		}
		
		
		
		
		public global::hxDaedalus.data.Face _fromFace;
		
		public global::hxDaedalus.data.Edge _nextEdge;
		
		public global::hxDaedalus.data.Edge _resultEdge;
		
		public virtual global::hxDaedalus.data.Face set_fromFace(global::hxDaedalus.data.Face @value) {
			this._fromFace = @value;
			this._nextEdge = this._fromFace.get_edge();
			return @value;
		}
		
		
		public virtual global::hxDaedalus.data.Edge next() {
			if (( this._nextEdge != null )) {
				this._resultEdge = this._nextEdge;
				this._nextEdge = this._nextEdge.get_nextLeftEdge();
				if (( this._nextEdge == this._fromFace.get_edge() )) {
					this._nextEdge = null;
				}
				
			}
			else {
				this._resultEdge = null;
			}
			
			return this._resultEdge;
		}
		
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 114842841:
					{
						this._resultEdge = ((global::hxDaedalus.data.Edge) (@value) );
						return @value;
					}
					
					
					case 913401391:
					{
						this._nextEdge = ((global::hxDaedalus.data.Edge) (@value) );
						return @value;
					}
					
					
					case 1763146374:
					{
						this._fromFace = ((global::hxDaedalus.data.Face) (@value) );
						return @value;
					}
					
					
					case 562135847:
					{
						this.set_fromFace(((global::hxDaedalus.data.Face) (@value) ));
						return @value;
					}
					
					
					default:
					{
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1224901875:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "next", 1224901875)) );
					}
					
					
					case 1804884644:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "set_fromFace", 1804884644)) );
					}
					
					
					case 114842841:
					{
						return this._resultEdge;
					}
					
					
					case 913401391:
					{
						return this._nextEdge;
					}
					
					
					case 1763146374:
					{
						return this._fromFace;
					}
					
					
					default:
					{
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_invokeField(string field, int hash, object[] dynargs) {
			unchecked {
				switch (hash) {
					case 1224901875:
					{
						return this.next();
					}
					
					
					case 1804884644:
					{
						return this.set_fromFace(((global::hxDaedalus.data.Face) (dynargs[0]) ));
					}
					
					
					default:
					{
						return base.__hx_invokeField(field, hash, dynargs);
					}
					
				}
				
			}
		}
		
		
		public override void __hx_getFields(global::HxArray<string> baseArr) {
			baseArr.push("_resultEdge");
			baseArr.push("_nextEdge");
			baseArr.push("_fromFace");
			baseArr.push("fromFace");
			base.__hx_getFields(baseArr);
		}
		
		
	}
}


