// Generated by Haxe 4.3.6

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace haxe.iterators {
	public class ArrayKeyValueIterator<T> : global::haxe.lang.HxObject, global::haxe.iterators.ArrayKeyValueIterator {
		
		public ArrayKeyValueIterator(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public ArrayKeyValueIterator(global::HxArray<T> array) {
			global::haxe.iterators.ArrayKeyValueIterator<object>.__hx_ctor_haxe_iterators_ArrayKeyValueIterator<T>(((global::haxe.iterators.ArrayKeyValueIterator<T>) (this) ), ((global::HxArray<T>) (array) ));
		}
		
		
		protected static void __hx_ctor_haxe_iterators_ArrayKeyValueIterator<T_c>(global::haxe.iterators.ArrayKeyValueIterator<T_c> __hx_this, global::HxArray<T_c> array) {
			__hx_this.array = array;
		}
		
		
		public static object __hx_cast<T_c_c>(global::haxe.iterators.ArrayKeyValueIterator me) {
			return ( (( me != null )) ? (me.haxe_iterators_ArrayKeyValueIterator_cast<T_c_c>()) : default(object) );
		}
		
		
		public virtual object haxe_iterators_ArrayKeyValueIterator_cast<T_c>() {
			if (global::haxe.lang.Runtime.eq(typeof(T), typeof(T_c))) {
				return this;
			}
			
			global::haxe.iterators.ArrayKeyValueIterator<T_c> new_me = new global::haxe.iterators.ArrayKeyValueIterator<T_c>(((global::haxe.lang.EmptyObject) (global::haxe.lang.EmptyObject.EMPTY) ));
			global::HxArray<string> fields = global::HxReflect.fields(this);
			int i = 0;
			while (( i < fields.length )) {
				string field = fields[i++];
				global::HxReflect.setField(new_me, field, global::HxReflect.field(this, field));
			}
			
			return new_me;
		}
		
		
		public global::HxArray<T> array;
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 630156697:
					{
						this.array = ((global::HxArray<T>) (global::HxArray<object>.__hx_cast<T>(((global::HxArray) (@value) ))) );
						return @value;
					}
					
					
					default:
					{
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 630156697:
					{
						return this.array;
					}
					
					
					default:
					{
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override void __hx_getFields(global::HxArray<string> baseArr) {
			baseArr.push("array");
			base.__hx_getFields(baseArr);
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace haxe.iterators {
	[global::haxe.lang.GenericInterface(typeof(global::haxe.iterators.ArrayKeyValueIterator<object>))]
	public interface ArrayKeyValueIterator : global::haxe.lang.IHxObject, global::haxe.lang.IGenericObject {
		
		object haxe_iterators_ArrayKeyValueIterator_cast<T_c>();
		
	}
}


